IF NOT EXISTS (SELECT 1 FROM FUNCIONARIO WHERE PK_FUNCIONARIO = @FUNCIONARIO)
	THROW 51000, 'Não foi localizado nenhum funcionário com esse código.', 1

DELETE FROM FUNCIONARIO WHERE PK_FUNCIONARIO = @FUNCIONARIO