IF NOT EXISTS (SELECT 1 FROM ESTADO WHERE PK_ESTADO = @ESTADO) AND @ESTADO <> '0'
	THROW 51000, 'Não foi localizado nenhum estado com esse código.', 1

INSERT INTO FUNCIONARIO
(
	NOME
,	EMAIL
,	DATANASCIMENTO
,	SALARIO
,	FK_ESTADO
)
VALUES
(
	@NOME
,	@EMAIL
,	@DATANASCIMENTO
,	CAST(@SALARIO AS DECIMAL(8,2))
,	CAST(IIF(@ESTADO = '0', NULL, @ESTADO) AS INT)
)