IF NOT EXISTS (SELECT 1 FROM FUNCIONARIO WHERE PK_FUNCIONARIO = @CODIGO)
	THROW 51000, 'Não foi localizado nenhum funcionário com esse código.', 1

UPDATE FUNCIONARIO
SET	NOME			 = @NOME
,	EMAIL			 = @EMAIL
,	DATANASCIMENTO	 = @DATANASCIMENTO
,	SALARIO			 = CAST(@SALARIO AS DECIMAL(8,2))
,	FK_ESTADO		 = CAST(IIF(@ESTADO = '0', NULL, @ESTADO) AS INT)
WHERE PK_FUNCIONARIO = @CODIGO